---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [yaml]
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.10.0
    hooks:
      - id: ansible-lint
