---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [yaml]
  - repo: https://github.com/ansible/ansible-lint
    rev: b7fb66a
    hooks:
      - id: ansible-lint
        args: [-c=.ansible_lint.yml]
