language: c
os: linux
sudo: required
dist: trusty

env:
  global:
    - REPO_NAME=edran/.dotfiles
    - DOT_PATH=~/.dotfiles

install:
  - sudo apt-get install git

before_script:
  mv $REPO_NAME $DOT_PATH
  cd $DOT_PATH

script:
  sudo ./install.sh
