---
os: linux
dist: trusty  # TravisCI doesn't support Xenial directly yet
sudo: required  # Dockerfile requires sudo

services:
  - docker

script:
  - export GIT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - docker build . --build-arg git_branch=$GIT_BRANCH
