---
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1

services:
  - docker

script:
  - export GIT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - docker build . --build-arg git_branch=$GIT_BRANCH
