language: c
os: linux
sudo: required
dist: trusty

env:
  global:
    - REPO_NAME="edran/.dotfiles"
    - CI_PATH=`pwd`/$REPO_NAME
    - DOT_PATH=~/.dotfiles

install:
  - sudo apt-get install git

before_script:
  - pwd
  - mv $CI_PATH $DOT_PATH
  - cd $DOT_PATH

script:
  sudo ./install.sh
