---
language: python
python: "2.7"
os: linux
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  - ansible-playbook -i ~/.dotfiles/ansible/inventory ~/.dotfiles/ansible/ubuntu.yml
