---
language: python
python: "2.7"
os: linux
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  - cd install
  - sudo ./install.sh -n
  - ansible-playbook -i ../ansible/inventory ../ansible/ubuntu.yml --sudo
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
