---

- name: Remove Home directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  with_items:
    - "Desktop"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Pictures"
    - "Videos"
    - "examples.desktop"
    - "Public"
    - "Templates"

- name: Create development home directory
  file:
    path: "{{ ansible_env.HOME }}/{{item}}"
    state: directory
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0755
  with_items:
    - "desktop"
    - "docs"
    - "downloads"
    - "media/music"
    - "media/images"
    - "media/videos"
    - "lab"

- name: Symlink dotfiles
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/{{ item.dot }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ linking_paths }}"

- name:  Add trim to all SSDs
  lineinfile:
    dest: /etc/cron.weekly/fstrim
    backup: True
    backrefs: True
    state: present
    regexp: '^(exec\sfstrim\-all\s*(?!\-\-no\-model\-check))$'
    line: 'exec fstrim-all --no-model-check'
  become: yes
  become_method: sudo

- replace: dest=/etc/hosts regexp='(\s+)old\.host\.name(\s+.*)?$' replace='\1new.host.name\2' backup=yes

# - name: Add gsettings
#   gsetting: user="{{ansible_user_id}}"
#             key="{{item.key}}"
#             value="{{item.value}}"
#   with_items: "{{ gsettings_settings }}"
