---
- name: Remove Home directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  with_items:
    - "Desktop"
    - "Documents"
    - "Downloads"
    - "Music"
    - "Pictures"
    - "Videos"
    - "examples.desktop"
    - "Public"
    - "Templates"

- name: Create development home directory
  file:
    path: "{{ ansible_env.HOME }}/{{item}}"
    state: directory
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0755
  with_items:
    - "desktop"
    - "docs"
    - "downloads"
    - "media/music"
    - "media/images"
    - "media/videos"
    - "lab"

- name: Remove .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: absent

- name: Symlink dotfiles
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/{{ item.dot }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ linking_paths }}"

- name: Check source-code-pro directory
  stat:
    path: "{{ ansible_env.HOME }}/.fonts/adobe-fonts/source-code-pro/"
  register: font_path
  changed_when: false

- name: Download source-code-pro
  git:
    repo: https://github.com/adobe-fonts/source-code-pro
    version: release
    dest: "{{ ansible_env.HOME }}/.fonts/adobe-fonts/source-code-pro"
  when: not font_path.stat.exists

- name: Update font cache
  command: "fc-cache -f -v"
  become: yes
  become_method: sudo
  when: not font_path.stat.exists
