---
- name: Symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/../{{ item.dot }}"
    dest: "{{ ansible_env.HOME }}/.{{ item.dest }}"
    state: link
    force: yes
  with_items: linking_paths

- name: Add trim to all SSDs
  command: sed -ie 's/^exec fstrim-all*$/& --no-model-check/g' file
  sudo: yes

- include: gsettings.yml
