#+TITLE: Doom Emacs Configuration
#+AUTHOR: Nantas Nardelli
#+LANGUAGE: en
#+PROPERTY: header-args :tangle yes :cache yes :results silent :comments link

* Preface
I have been using Emacs as my editor for more than a decade -- well before I
started calling myself a programmer -- and the journey has been quite the ride
so far.

My configuration has gone through many [[https://www.emacswiki.org/emacs/DotEmacsBankruptcy][bankruptcies]], including a few that
predate any usage (and knowledge!) of version control on my part. It's current
form, which most certainly is not its final (but which I hope to be its
/present/ for at least a few more years), is based on the amazing =doom emacs=
and =org-mode=. Thanks to these frameworks, it is much, much slimmer than it
used to be at various points of its history.

Which is both good and bad. But /c'est la vie/ :)

** Basic usage info
In theory, the latest version of =doom emacs= should be able to simply run this
configuration. The first time, it needs to be generated via:

#+begin_src sh
$ doom sync  # generates config.el from tangling config.org
#+end_src

Afterwards, this org file will be tangled upon save, hopefully. If it's not the
case, =doom refresh= should do the job.

My main dev setup is a MBP running a heavily configured =MacOS 10.14=, but most
of this config should behave properly on modern linux distros so long as the
environment is configured similarly to what is provided by my [[https://github.com/edran/.dotfiles][dotfiles]].

** Known issues
This config is a /Forever Work In Progress™/, and thus there are things that I
wish were fixed / implemented that either I haven't had the time to tackle
and/or have the capabilities to properly do so.
*** org headers are indented
This sucks. I want as much horizontal space as possible without having to
soft-wrap everything.
*** conda environments interact weirdly with lsp
Calling =conda-env-activate= doesn't restart the lsp server. Worse,
=lsp-restart-workspace= seems to successfully kill the server, but a further
=lsp= call is required for the server to be up again.
**** TODO Make =conda-env-activate= automatically call =lsp-restart-workspace=
**** TODO Fix =lsp-restart-workspace= so that it actually restarts the lsp server
*** I would like hard wrap to work its magic on the paragraph automatically
Rather than the last sentence / lines.

* Essential configuration

Lexical binding can result into faster execution of this file (see [[https://nullprogram.com/blog/2016/12/22/][this blog
post]]), so we activate it.

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

** Personal info
#+begin_src emacs-lisp :tangle yes

;;;; deets
(setq user-full-name "Nantas Nardelli"
      user-mail-address "nantas.nardelli@gmail.com")
#+end_src

** Basic paths

#+begin_src emacs-lisp :tangle yes
(setq
      org-directory "~/org"
      projectile-project-search-path '("~/lab")  ;; this is not recursive, sadly
      magit-repository-directories '(("~/lab" . 2)))
#+end_src

** Setting up theme
#+begin_src emacs-lisp :tangle yes

;;;; UI
(setq doom-theme 'doom-dracula
      doom-font (font-spec :family "monospace" :size 12)
      ;; doom-variable-pitch-font
      ;; doom-big-font

      ;; To be re-enabled when I get a better machine.
      display-line-numbers-type nil)

#+end_src
**  UX changes

#+begin_src emacs-lisp :tangle yes
;;;; UX
(setq doom-scratch-initial-major-mode 'lisp-interaction-mode)

;; Switch to new window when splitting
(setq evil-split-window-below t
      evil-vsplit-window-right t

      ;; isearch
      isearch-lazy-count t
      isearch-allow-scroll 'unlimited

      ;; magit
      magit-save-repository-buffers 'dontask
      ;; Don't restore window config after quitting magit
      magit-inhibit-save-previous-winconf t)

(add-to-list 'ispell-skip-region-alist '(org-property-drawer-re))
(add-to-list 'ispell-skip-region-alist '("~" "~"))
(add-to-list 'ispell-skip-region-alist '("=" "="))

#+end_src

** org stuff

#+begin_src emacs-lisp :tangle yes
(after! org
  (map! :localleader
        :map org-mode-map
        "M-n" #'org-next-visible-heading
        "M-p" #'org-previous-visible-heading))
#+end_src
#+begin_src emacs-lisp :tangle yes

;;;; langs
;;;; org
(setq org-archive-location (concat
                            (file-name-as-directory org-directory)
                            ".archive/%s::")
      org-roam-directory (concat
                          (file-name-as-directory org-directory)
                          "notes/")
      org-ellipsis " ▼ "
      org-bullets-bullet-list '("☰" "☱" "☲" "☳" "☴" "☵" "☶" "☷" "☷" "☷" "☷")

      org-babel-load-languages '((dot . t)
                                 (emacs-lisp . t)
                                 (python . t)
                                 (R . t))
      ;; org-src-window-setup 'current-window
      org-return-follows-link t
      )
#+end_src


#+begin_src emacs-lisp :tangle yes
;;;; python
(setq conda-anaconda-home "~/.conda")
#+end_src
