(spacemacs/set-leader-keys-for-major-mode 'lua-mode "d" 'lua-search-documentation)
(spacemacs/set-leader-keys-for-major-mode 'lua-mode "sb" 'lua-send-buffer)
(spacemacs/set-leader-keys-for-major-mode 'lua-mode "sf" 'lua-send-defun)
(spacemacs/set-leader-keys-for-major-mode 'lua-mode "sl" 'lua-send-current-line)
(spacemacs/set-leader-keys-for-major-mode 'lua-mode "sr" 'lua-send-region)
