- name: Add apt repositories
  sudo: yes
  apt_repository:
    state: present
    repo: "{{ item }}"
  with_items: "{{ apt_repos }}"
  register: ansible_added

- name: apt update cache
  apt:
    update_cache: yes
  when: ansible_added.changed

- name: Install apt packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"
