- include: apt.yml

# after apt.yml
- name: set gcc-4.8 as default
  alternatives: name=gcc link=/usr/bin/gcc path=/usr/bin/gcc-4.8
  become: yes
  become_method: sudo

- name: set g++-4.8 as default
  alternatives: name=g++ link=/usr/bin/g++ path=/usr/bin/g++-4.8
  become: yes
  become_method: sudo
