- name: Add mopidy APT repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'deb http://apt.mopidy.com/ stable main contrib non-free'
    state: present

- name: Import Mopidy GPG key
  become: yes
  become_method: sudo
  apt_key:
    id: 271D2943
    url: "https://apt.mopidy.com/mopidy.gpg"
    state: present

- name: apt update cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: Install mopidy
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - mopidy
    - ncmpcpp
    - libspotify-dev

- name: Install mopidy extensions
  become: yes
  become_method: sudo
  pip:
    executable: pip
    name: "{{ item }}"
    state: latest
  with_items:
    - mopidy-scrobbler
    - mopidy-spotify
    - pyspotify
    - mopidy-spotify-web
    - mopidy-gmusic
    - mopidy-somafm
    - mopidy-youtube
    - mopidy-soundcloud
    - mopidy-local-images
    - mopidy-local-sqlite

- name: Disable mopidy service
  become: yes
  become_method: sudo
  service:
    name: mopidy
    enabled: false
    state: stopped

- name: Check secret.conf exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/mopidy/secret.conf"
  register: secret_path

- name: Copy secret file to mopidy config folder
  copy:
    src: "files/secret.conf"
    dest: "{{ ansible_env.HOME }}/.config/mopidy/secret.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  when: secret_path.stat.exists == False

