- name: Add mopidy APT repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'deb http://apt.mopidy.com/ stable main contrib non-free'
    state: present

- name: Import Mopidy GPG key
  become: yes
  become_method: sudo
  apt_key:
    id: 271D2943
    url: "https://apt.mopidy.com/mopidy.gpg"
    state: present

- name: Install mopidy
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - mopidy
    - ncmpcpp
    - libspotify-dev

- name: Install mopidy extensions
  become: yes
  become_method: sudo
  pip:
    executable: pip
    name: "{{ item }}"
    state: latest
  with_items:
    - mopidy-scrobbler
    - mopidy-spotify
    - mopidy-spotify-tunigo
    - mopidy-gmusic
    - mopidy-somafm
    - mopidy-youtube
    - mopidy-soundcloud
    - mopidy-local-images

- name: Authorize mopidy to play sound over pulse
  become: yes
  become_method: sudo
  user:
    name: mopidy
    groups: pulse-access
    append: yes

- name: Ensures mopidy daemon is enabled and started
  become: yes
  become_method: sudo
  service:
    name: mopidy
    enabled: yes
    state: started
