---

- name: homebrew | Enable Homebrew bundle tap
  homebrew_tap:
    name: homebrew/bundle

- name: homebrew | Check if Brewfile contains updates
  shell: brew bundle check --file="{{ role_path }}/files/Brewfile"
  register: bundle_check_result
  ignore_errors: true  # TODO check why this is needed

- name: homebrew | Install apps using Brewfile
  shell: brew bundle install --file="{{brewfile|default(Brewfile)}}"
  when: bundle_check_result is failed
