---
- name: mosh | Check current installation
  command: which mosh
  register: mosh_present
  failed_when: mosh_present.rc > 1
  changed_when: mosh_present.rc == 1

- name: mosh | Add repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: "ppa:keithw/mosh-dev"
  register: ansible_added
  when: mosh_present.changed

- name: mosh | Install Mosh
  become: yes
  become_method: sudo
  apt:
    pkg: mosh
    state: present
    update_cache: yes
  when: mosh_present.changed
