---

- name: tmux | Ensure tmux is installed
  homebrew:
    pkg: tmux 
    state: present

- name: tmux | Clone TPM into homedir
  git:
    repo: "git://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_env.HOME}}/.tmux/plugins/tpm"
    force: no
    accept_hostkey: yes
