- include: apt.yml

- name: Update pip and pip3
  become: yes
  become_method: sudo
  pip:
    name: pip
    executable: "{{ item }}"
    state: latest
  with_items: "{{ pip_executables }}"

- name: Install python packages
  become: yes
  become_method: sudo
  pip:
    name: "{{ item }}"
    executable: pip
    state: latest
  with_items: "{{ pip_packages }}"

- include: vwrapper.yml
