- name: ag | Check current installation
  command: "ag --version"
  sudo: yes
  register: result
  ignore_errors: True

- name: ag | Install build deps
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev
  when: result.rc !=0

- name: ag | Checkout
  git:
    repo: "git://github.com/ggreer/the_silver_searcher"
    dest: "/tmp/ag"
    force: no
    accept_hostkey: yes
  when: result.rc !=0

- name: ag | Make
  command: "./build.sh"
  args:
    chdir: "/tmp/ag"
  when: result.rc !=0

- name: ag | Install
  command: "make install"
  sudo: yes
  args:
    chdir: "/tmp/ag"
  when: result.rc !=0
