# - name: Add apt keys via URL
#   sudo: yes
#   apt_key: 
#     url={{ item.url }}
#   with_items: "{{ apt_keys_url | default([]) }}"

# - name: Add apt keys via id
#   sudo: yes
#   apt_key:
#     keyserver={{ item.keyserver }}
#     id={{ item.id }}
#   with_items: "{{ apt_keys_id | default([]) }}"


- name: Add apt repositories
  sudo: yes
  apt_repository: "state=present repo='{{ item }}'"
  with_items: "{{ apt_repos | default([]) }}"
  register: ansible_added

- name: apt update cache
  apt:
    update_cache: yes
  when: ansible_added.changed

- name: Install apt packages
  sudo: yes
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items: "{{ apt_packages | default([]) }}"
