---
- name: Add apt repositories
  become: yes
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
  with_items: "{{ apt_repos }}"
  register: ansible_added

- name: apt update cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  when: ansible_added.changed

- name: Install apt packages
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items: "{{ apt_packages }}"

