- name: Docker | Check if is present
  command: test -x /usr/bin/docker
  ignore_errors: yes
  register: docker_present
  failed_when: docker_present.rc > 1
  changed_when: docker_present.rc == 1

- name: Docker | Add docker gpg keys
  shell: wget -qO- https://get.docker.com/gpg | sudo apt-key add -
  when: docker_present|failed
  become: yes
  become_method: sudo

- name: Docker | Install docker
  shell: wget -qO- https://get.docker.com/ | sh
  when: docker_present|failed
  become: yes
  become_method: sudo

- name: Docker | Add current user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes
  become_method: sudo
  when: docker_present|failed
