---
- name: Emacs | Check current installation
  command: "emacs-{{emacs_version}} --version"
  ignore_errors: yes
  register: emacs_present

- name: Emacs | Install build-essential
  package:
    name: build-essential
    state: present

- name: Emacs | Install build deps
  apt:
    pkg: emacs24
    state: build-dep
  when: emacs_present|failed

- name: Emacs | Download source
  get_url:
    url: "http://ftp.heanet.ie/mirrors/gnu/emacs/emacs-{{emacs_version}}.tar.gz"
    dest: "/tmp/emacs-{{emacs_version}}.tar.gz"
  when: emacs_present|failed

- name: Emacs | Untar source
  unarchive:
    copy: no
    src: "/tmp/emacs-{{emacs_version}}.tar.gz"
    dest: "/opt"
    creates: "/opt/emacs-{{emacs_version}}"
  when: emacs_present|failed

- name: Emacs | Configure source
  command: ./configure
  args:
    chdir: "/opt/emacs-{{emacs_version}}"
    creates: "/opt/emacs-{{emacs_version}}/Makefile"
  when: emacs_present|failed

- name: Emacs | Build source
  command: make
  args:
    chdir: "/opt/emacs-{{emacs_version}}"
    creates: "/opt/emacs-{{emacs_version}}/src/emacs"
  when: emacs_present|failed

- name: Emacs | Install emacs
  command: make install
  args:
    chdir: "/opt/emacs-{{emacs_version}}"
    creates: "/usr/local/bin/emacs"
  become: yes
  become_method: sudo
  when: emacs_present|failed

- name: Emacs | Check .emacs.d
  stat:
    path: "{{ ansible_env.HOME }}/.emacs.d"
  register: emacs_path

- name: Emacs | Download Spacemacs 
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    accept_hostkey: yes
    recursive: yes
  when: not emacs_path.stat.exists
