- name: i3blocks | Check current installation
  command: "i3blocks -V"
  become: yes
  become_method: sudo
  register: result
  failed_when: result.rc > 1
  changed_when: result.rc == 1
  ignore_errors: True

- name: i3blocks | Checkout
  git:
    repo: "git://github.com/vivien/i3blocks"
    dest: "/tmp/i3blocks"
    force: no
    accept_hostkey: yes
  when: result.rc !=0

- name: i3blocks | Make
  command: "make clean all"
  args:
    chdir: "/tmp/i3blocks"
  when: result.rc !=0

- name: i3blocks | Install
  command: "make install"
  become: yes
  become_method: sudo
  args:
    chdir: "/tmp/i3blocks"
  when: result.rc !=0
