---
- name: Create development home directory
  file:
    path: "{{ ansible_env.HOME }}/lab"
    state: directory
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"

- include: apt.yml
- include: xcape.yml
- include: ag.yml
- include: docker.yml
- include: emacs.yml
- include: tmux.yml
- include: rofi.yml
- include: i3blocks.yml

- name: Check urxvt-perls
  stat:
    path: "{{ ansible_env.HOME }}/.dotfiles/dots/urxvt/ext"
  register: perls

- name: Clone urxvt-perls
  git:
    repo: https://github.com/muennich/urxvt-perls
    dest: "{{ ansible_env.HOME }}/.dotfiles/dots/urxvt/ext"
    accept_hostkey: yes
    recursive: yes
    version: master
  when: not perls.stat.exists
