---
- name: Create development home directory
  file:
    path: "{{ ansible_env.HOME }}/Dev"
    state: directory

- include: apt.yml
- include: xcape.yml
- include: ag.yml
- include: docker.yml
- include: emacs.yml
- include: tmux.yml
