- name: rofi | Check current installation
  command: "rofi --version"
  become: yes
  become_method: sudo
  register: result
  failed_when: result.rc > 1
  changed_when: result.rc == 1
  ignore_errors: True

- name: rofi | Install build deps
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - automake
    - pkg-config
    - libpango1.0-dev
    - libpangocairo-1.0-0
    - libcairo2-dev
    - libglib2.0-0
    - libstartup-notification0-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libxcb-xkb-dev
    - libxcb-xinerama0-dev
    - libxcb1-dev
    - libxcb-util0-dev
    - libxcb-xrm-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
  when: result.rc !=0

- name: rofi | Checkout
  git:
    repo: "git://github.com/DaveDavenport/rofi"
    dest: "/tmp/rofi"
    force: no
    accept_hostkey: yes
    recursive: yes
  when: result.rc !=0

- name: rofi | Auto reconf
  command: "autoreconf -i"
  args:
    chdir: "/tmp/rofi"
  when: result.rc !=0


- name: rofi | Create build dir
  file:
    path: "/tmp/rofi/build"
    state: directory
    mode: 0755
  when: result.rc !=0

- name: rofi | Configure
  command: "../configure"
  args:
    chdir: "/tmp/rofi/build"
  when: result.rc !=0

- name: rofi | Make
  command: "make"
  args:
    chdir: "/tmp/rofi/build"
  when: result.rc !=0

- name: rofi | Install
  command: "make install"
  become: yes
  become_method: sudo
  args:
    chdir: "/tmp/rofi/build"
  when: result.rc !=0
