---
- name: Tmux | Check current installation
  command: "tmux -V"
  ignore_errors: yes
  register: tmux_present
  failed_when: tmux_present.rc > 0

- name: Tmux | Install build-essential 
  become: yes
  become_method: sudo
  package:
    name: build-essential
    state: present
  when: tmux_present|failed

- name: Tmux | Install build deps
  become: yes
  become_method: sudo
  apt:
    pkg: tmux
    state: build-dep
  when: tmux_present|failed

- name: Tmux | Download source
  become: yes
  become_method: sudo
  get_url:
    url: "https://github.com/tmux/tmux/releases/download/2.2/tmux-{{tmux_version}}.tar.gz"
    dest: "/tmp/tmux-{{tmux_version}}.tar.gz"
  when: tmux_present|failed

- name: Tmux | Untar
  become: yes
  become_method: sudo
  unarchive:
    copy: no
    src: "/tmp/tmux-{{tmux_version}}.tar.gz"
    dest: "/opt"
    creates: "/opt/tmux-{{tmux_version}}"
  when: tmux_present|failed

- name: Tmux | Configure
  become: yes
  become_method: sudo
  command: ./configure
  args:
    chdir: "/opt/tmux-{{tmux_version}}"
    creates: "/opt/tmux-{{tmux_version}}/Makefile"
  when: tmux_present|failed

- name: Tmux | Build
  become: yes
  become_method: sudo
  command: make
  args:
    chdir: "/opt/tmux-{{tmux_version}}"
    creates: "/opt/tmux-{{tmux_version}}/src/tmux"
  when: tmux_present|failed

- name: Tmux | Install
  become: yes
  become_method: sudo
  command: make install
  args:
    chdir: "/opt/tmux-{{tmux_version}}"
    creates: "/usr/local/bin/tmux"
  when: tmux_present|failed
