- name: get currently installed xcape version
  command: "xcape --version"
  sudo: yes
  register: result
  ignore_errors: True

- name: Install xcape build dependencies
  sudo: yes
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - git
    - gcc
    - make
    - pkg-config
    - libx11-dev
    - libxtst-dev
    - libxi-dev
  when: result.rc !=0

- name: Checkout xcape
  git:
    repo: "git://github.com/alols/xcape.git"
    dest: "/tmp/xcape"
    force: no
    accept_hostkey: yes
  when: result.rc !=0

- name: Make xcape
  command: "make"
  args:
    chdir: /tmp/xcape
  when: result.rc !=0

- name: Install xcape
  command: "make install"
  sudo: yes
  args:
    chdir: /tmp/xcape
  when: result.rc !=0
