- name: xcape | Check current version
  command: "xcape --version"
  sudo: yes
  register: result
  ignore_errors: True

- name: xcape | Install build deps
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - gcc
    - make
    - pkg-config
    - libx11-dev
    - libxtst-dev
    - libxi-dev
  when: result.rc !=0

- name: xcape | Checkout
  git:
    repo: "git://github.com/alols/xcape.git"
    dest: "/tmp/xcape"
    force: no
    accept_hostkey: yes
  when: result.rc !=0

- name: xcape | Make
  command: "make"
  args:
    chdir: "/tmp/xcape"
  when: result.rc !=0

- name: xcape | Install
  command: "make install"
  sudo: yes
  args:
    chdir: "/tmp/xcape"
  when: result.rc !=0
