---
linking_paths:
  - {dot: "dots/inputrc", dest: ".inputrc"}
  - {dot: "dots/profile", dest: ".profile"}
  - {dot: "dots/gitconfig", dest: ".gitconfig"}
  - {dot: "dots/bashrc", dest: ".bashrc"}
  - {dot: "dots/bin", dest: "bin"}
  - {dot: "dots/fonts", dest: ".fonts"}
  - {dot: "dots/tmux.conf", dest: ".tmux.conf"}
  - {dot: "dots/vimrc", dest: ".vimrc"}
  - {dot: "dots/Xresources", dest: ".Xresources"}
  - {dot: "dots/dmrc", dest: ".dmrc"}
  - {dot: "dots/ncmpcpp", dest: ".ncmpcpp"}
  - {dot: "dots/i3", dest: ".i3"}
  - {dot: "dots/spacemacs", dest: ".spacemacs.d"}
  - {dot: "dots/weechat/", dest: ".weechat"}
  # - {dot: "dots/urxvt/", dest: ".urxvt"}

home_dirs_add:
  - "desktop"
  - "docs"
  - "downloads"
  - "media/music"
  - "media/images"
  - "media/videos"
  - "lab"

home_dirs_remove:
  - "Desktop"
  - "Documents"
  - "Downloads"
  - "Music"
  - "Pictures"
  - "Videos"
  - "examples.desktop"
  - "Public"
  - "Templates"
