---

backup_dir: "{{ ansible_user_dir }}/.dotfiles_ansible_backup"

dots_map:
  - {src: "dots/bin", dest: "bin"}
  # shell config
  - {src: "dots/profile", dest: ".profile"}
  - {src: "dots/zsh", dest: ".zsh"}
  - {src: "dots/bash/bashrc", dest: ".bashrc"}
  - {src: "dots/bash/bash_profile", dest: ".bash_profile"}
  - {src: "dots/inputrc", dest: ".inputrc"}
  # tooling
  - {src: "dots/ssh/config", dest: ".ssh/config"}
  - {src: "dots/git", dest: ".config/git"}
  - {src: "dots/vimrc", dest: ".vimrc"}
  - {src: "dots/condarc", dest: ".condarc"}
  - {src: "dots/tmux/tmux.conf", dest: ".tmux.conf"}

ubuntu_linking_paths:
  - {dot: "dots/fonts", dest: ".fonts"}
  - {dot: "dots/Xresources", dest: ".Xresources"}
  - {dot: "dots/dmrc", dest: ".dmrc"}
  - {dot: "dots/ncmpcpp", dest: ".ncmpcpp"}
  - {dot: "dots/i3", dest: ".i3"}
  - {dot: "dots/weechat/", dest: ".weechat"}

ubuntu_home_dirs_add:
  - "desktop"
  - "docs"
  - "downloads"
  - "media/music"
  - "media/images"
  - "media/videos"
  - "lab"

osx_home_dirs_add:
  - "lab"
  - "Pictures/screenshots"

ubuntu_home_dirs_remove:
  - "Desktop"
  - "Documents"
  - "Downloads"
  - "Music"
  - "Pictures"
  - "Videos"
  - "examples.desktop"
  - "Public"
  - "Templates"
