- name: Add apt keys via URL
  become: yes
  become_method: sudo
  apt_key: 
    url: "{{ item.url|default() }}"
    id: "{{ item.id|default() }}"
  with_items: "{{ apt_keys_url }}"

- name: Add apt keys via id
  become: yes
  become_method: sudo
  apt_key:
    keyserver: "{{ item.keyserver|default() }}"
    id: "{{ item.id|default() }}"
  with_items: "{{ apt_keys_id }}"

- name: Add apt repositories
  become: yes
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
  with_items: "{{ apt_repos }}"
  register: ansible_added

- name: apt update cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  when: ansible_added.changed

- name: Install apt packages
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items: "{{ apt_packages }}"

