- name: Add apt keys via URL
  sudo: yes
  apt_key: 
    url: "{{ item.url|default() }}"
  with_items: "{{ apt_keys_url }}"

- name: Add apt keys via id
  sudo: yes
  apt_key:
    keyserver: "{{ item.keyserver|default() }}"
    id: "{{ item.id|default() }}"
  with_items: "{{ apt_keys_id }}"

- name: Add apt repositories
  sudo: yes
  apt_repository:
    state: present
    repo: "{{ item }}"
  with_items: "{{ apt_repos }}"
  register: ansible_added

- name: "apt | ensure previous repository for Google Chrome is absent"
  sudo: yes
  apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: absent

# workaround for missing x86 distribution
- name: "apt | ensure Google chrome repo present, using a workaround for missing x86 distribution"
  sudo: yes
  copy:
    content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    dest: "/etc/apt/sources.list.d/google-chrome.list"

- name: apt update cache
  apt:
    update_cache: yes
  when: ansible_added.changed

- name: Install apt packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"

