- name: Make sure gnome-keyring start at login part 1
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/pam.d/login
    backup: True
    backrefs: True
    state: present
    regexp: 'auth\s*optional\s*pam_gnome_keyring\.so$'
    line: 'auth optional pam_gnome_keyring.so'

- name: Make sure gnome-keyring start at login part 2
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/pam.d/login
    backup: True
    backrefs: True
    state: present
    regexp: '^session\s*optional\s*pam_gnome_keyring\.so\s*auto_start$'
    line: 'session  optional  pam_gnome_keyring.so auto_start'

- name: Make sure gnome-keyring start at login part 3
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/pam.d/passwd
    backup: True
    backrefs: True
    state: present
    regexp: '^password\s*optional\s*pam_gnome_keyring.so$'
    line: "password  optional  pam_gnome_keyring.so"
