- include: apt.yml
- include: zotero.yml
- include: harware.yml
- include: gnome.yml
  when: ansible_distribution == 'Ubuntu'

- name: Set urxvt as default terminal
  become: yes
  become_method: sudo
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt
