- include: apt.yml

- name: Check if Mendeley is installed
  command: dpkg-query -W mendeleydesktop
  register: mendeleydesktop_deb
  failed_when: mendeleydesktop_deb.rc > 1
  changed_when: mendeleydesktop_deb.rc == 1

- name: Download Mendeley
  get_url:
    url: "{{ mendeley_url }}"
    dest: "/tmp/mendeley.deb"
  when: mendeleydesktop_deb.rc == 1

- name: Install Mendeley
  become: yes
  become_method: sudo
  apt:
    deb: "/tmp/mendeley.deb"
  when: mendeleydesktop_deb.rc == 1

- name:  Add trim to all SSDs
  lineinfile:
    dest: /etc/cron.weekly/fstrim
    backup: True
    backrefs: True
    state: present
    regexp: '^(exec\sfstrim\-all\s*(?!\-\-no\-model\-check))$'
    line: 'exec fstrim-all --no-model-check'
  become: yes
  become_method: sudo

- name: Set urxvt as default terminal
  become: yes
  become_method: sudo
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt
