- name: Remove installation files
  file: path={{ item }} state=absent
  with_items:
    - "~/examples.desktop"
    - "~/Public"
    - "~/Templates"

- include: xcape.yml
- include: apt.yml
- include: gsetting.yml
