---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime

dockitems_persist: []
  # - name: "Emacs"
  #   path: "/Applications/Emacs.app/"
  #   pos: 5

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - doxygen
  # - gettext
  # - gifsicle
  - git
  - github/gh/gh
  # - go
  # - gpg
  # - httpie
  # - iperf
  # - libevent
  # - sqlite
  # - mcrypt
  # - nmap
  # - node
  - nvm
  - ssh-copy-id
  - cowsay
  # - readline
  # - openssl
  # - pv
  - wget
  # - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - railwaycat/emacsmacport

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - slack
  - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""
