---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime

dockitems_persist: []
# - name: "Emacs"
#   path: "/Applications/Emacs.app/"
#   pos: 5

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - railwaycat/emacsmacport

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - doxygen
  # - gettext
  # - gifsicle
  - git
  - github/gh/gh
  # - go
  # - gpg
  # - httpie
  # - iperf
  # - libevent
  # - sqlite
  # - mcrypt
  # - nmap
  # - node
  - nvm
  - ssh-copy-id
  - cowsay
  # - readline
  # - openssl
  # - pv
  - wget
  # - wrk
  - pyenv
  - diff-so-fancy
  - ripgrep
  - coreutils
  - fd
  - {name: emacs-mac, install_options: 'with-modules'}


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - slack
  - transmit
  - notion
  - linear-linear
  - signal
  - whatsapp
  - spotify
  - karabiner-elements

mas_installed_apps:
  - {id: 682658836, name: 'GarageBand'}
  - {id: 408981434, name: 'iMovie'}
  - {id: 409201541, name: 'Pages'}
  - {id: 409203825, name: 'Numbers'}
  - {id: 409183694, name: 'Keynote'}
  - {id: 419330170, name: 'Moom'}
  - {id: 1475387142, name: 'Tailscale'}
