---
- hosts: all
  vars:
    - downloads: ~/.ansible-downloads/

    - dockitems_remove:
        - Launchpad
        - Safari
        - Messages
        - Mail
        - Maps
        - Photos
        - FaceTime
        - Calendar
        - Contacts
        - Reminders
        - Notes
        - TV
        - Music
        - Podcasts
        - News
        - Keynote
        - Numbers
        - Pages
        - App Store
        - System Preferences

    - dockitems_persist:
        - name: Google Chrome
          path: /Applications/Google Chrome.app
          pos: 1
        - name: Emacs
          path: /Applications/Emacs.app
          pos: 2
        - name: iTerm
          path: /Applications/iTerm.app
          pos: 3
        - name: Slack
          path: /Applications/Slack.app
          pos: 4
        - name: Notion
          path: /Applications/Notion.app
          pos: 5
        - name: Linear
          path: /Applications/Linear.app
          pos: 6
        - name: Spotify
          path: /Applications/Spotify.app
          pos: 7
        - name: Whatsapp
          path: /Applications/Whatsapp.app
          pos: 8
        - name: Signal
          path: /Applications/Signal.app
          pos: 9
        - name: Anki
          path: /Applications/Anki.app
          pos: 10

    - homebrew_taps:
        - railwaycat/emacsmacport

    - homebrew_installed_packages:
        # - ansible # Installed via Pip.
        # GNU tools
        - autoconf
        - automake
        - bash # Because MacOS ships with an old version.
        - gpg
        # CLI essentials
        # NOTE: I'd much rather use only hunspell, howerver spell-fu on Emacs
        # does not support generating word lists with anything other than aspell
        # yet.
        - aspell
        - curl
        - fish
        - fzf
        - git
        - git-delta
        - git-lfs
        - gh
        - iperf3
        - nmap
        - nnn
        - ssh-copy-id
        - pv # Progress bar for pipes.
        - ripgrep
        - wget
        - tmux
        # Needed for Emacs
        # Remember to cp installation into /Applications
        - tree-sitter
        - jansson
        - libxml2
        - imagemagick
        - { name: emacs-mac,
            install_options: [
              with-modules,
              with-native-compilation,
              with-no-title-bars,
              with-xwidgets,
              with-emacs-big-sur-icon,
              with-librsvg,
              with-tree-sitter,
            ]
          }

        # Modern CLI tooling
        - angle-grinder # a.k.a. *agrinder*, log analysis.
        - bat # Replaces cat.
        - bottom # a.k.a. *btm*, replaces htop.
        - broot # a.k.a. *br*, replaces tree (?).
        - choose # cut
        - croc # Send files across devices.
        - ctop # Top for containers.
        - difftastic # a.k.a. *difft*, replaces diff.
        - glances # htop, again.
        - glow # Markdown on the terminal.
        - dive # Analyse docker images.
        - dust # du
        - entr # Run arbitrary commands on file changes.
        - exa # ls
        - duf # df
        - fd # find
        - fq # Explore binary files (like jq, ish).
        - fx # Interactive json tool.
        - gdu # ncdu
        - gping # Graphical ping.
        - hexyl # hexdump
        - htmlq # jq for html.
        - httpie # A friendly curl replacement.
        - hyperfine # Benchmarking tool.
        - jc # Convert various tools' output to json.
        - jless # JSON pager.
        - jo # Easily create json objects.
        - jq
        - lazydocker # TUI for docker.
        - lnav # Curses-based log viewing.
        - mtr # traceroute
        - pgcli # psql
        - procs # ps
        - sd # sed
        - tealdeer # A fast tldr client.
        - wrk # HTTP benchmarking.
        - xsv # CSV manipulator.
        - yq # jq for YAML.
        - zoxide # z, fast, autojump
        # Languages
        - go
        - nvm
        - pyenv
        # Fun / useful
        - gifsicle
        - fortune

    - homebrew_cask_appdir: /Applications
    - homebrew_cask_apps:
        - { name: nikitabobko/tap/aerospace, install_options: no-quarantine }
        - alfred
        - anki
        - chrysalis
        - docker
        - discord
        - dropbox
        - firefox
        - handbrake
        - iterm2
        - karabiner-elements
        - linear-linear
        - notion
        - postman
        - signal
        - slack
        - spotify
        - teamviewer
        - transmit
        - whatsapp
        - xbar
        - zotero

    - mas_installed_apps:
        - { id: 682658836, name: GarageBand }
        - { id: 408981434, name: iMovie }
        - { id: 409201541, name: Pages }
        - { id: 409203825, name: Numbers }
        - { id: 409183694, name: Keynote }
        - { id: 419330170, name: Moom }
        - { id: 1475387142, name: Tailscale }

    - dots_links:
        - { src: bin, dest: bin }
        - { src: fish, dest: .config/fish }
        - { src: doom.d, dest: .doom.d }
        - { src: git/config, dest: .gitconfig }
        - { src: git/ignore, dest: .gitignore }
        - { src: macos/aerospace.toml, dest: .aerospace.toml }
        - { src: macos/Moom.plist, dest: Library/Preferences/Moom.plist }
        - { src: macos/iterm2, dest: .iterm2 }
        - { src: macos/karabiner, dest: .config/karabiner }
        - { src: nethackrc, dest: .nethackrc }
        - { src: profile, dest: .profile }
        # TODO: this will normally fail. Needs a custom link task.
        - { src: ssh, dest: .ssh }
        - { src: tmux.conf, dest: .tmux.conf }
        - { src: vimrc, dest: .vimrc }
        - { src: zsh, dest: .zsh }
        - { src: zsh/.zprofile, dest: .zprofile }
        - { src: zsh/.zshenv, dest: .zshenv }
        - { src: zsh/.zshrc, dest: .zshrc }

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: [homebrew]
    - role: geerlingguy.mac.mas
      tags: [mas]

  tasks:
    - name: Link script to xbar
      file:
        src: "{{ inventory_dir }}/../dots/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
        state: link
      loop: "{{ dots_links }}"
      tags: [quick]

      tags: [quick]
    - name: Include Dock role.
      include_role:
        name: geerlingguy.mac.dock
        apply:
          tags: [dock]
      tags: [always]

    - name: Link script to xbar
      file:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/xbar/plugins/{{ item | basename }}"
        state: link
      with_fileglob:
        - "{{ inventory_dir }}/../dots/macos/xbar/*"
      tags: [quick]

    # TODO: requires killall Dock
    - name: Group windows by application in expose
      community.general.osx_defaults:
        domain: com.apple.dock
        key: expose-group-apps
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Autohide dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Make dock icons small
      community.general.osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: int
        value: 24
        state: present
      tags: [quick]
    - name: Use a simple window minimize animation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: genie
        state: present
      tags: [quick]
    - name: Add ability to scroll up on dock icon to see app instances
      community.general.osx_defaults:
        domain: com.apple.dock
        key: scroll-to-open
        type: bool
        value: true
        state: present
      tags: [quick]

    - name: Set OS languages 
      community.general.osx_defaults:
        key: applelanguages
        type: array
        value: 
          - en-us
      tags: [quick]

    # NOTE: requires killall SystemUIServer & a logout to take effect
    - name: Set displays to have separate spaces
      community.general.osx_defaults:
        domain: com.apple.spaces
        key: spans-displays
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Set default directory for screenshots
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "~/Desktop/screenshots"
        state: present
      tags: [quick]
    - name: Set default directory for Simulator screenshots
      community.general.osx_defaults:
        domain: com.apple.iphonesimulator
        key: ScreenShotSaveLocation
        type: string
        value: "~/Desktop/screenshots/simulator"
        state: present
      tags: [quick]

    # Finder
    - name: Show hidden files
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Show file extensions
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Show path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathbar
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Show folders on top
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXSortFoldersFirst
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Set default view to column
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: clmv
        state: present
      tags: [quick]
    - name: Empty bin after 30 days
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXRemoveOldTrashItems
        type: bool
        value: true
        state: present
      tags: [quick]
    - name: Disable warning when chaning a file extension
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXEnableExtensionChangeWarning
        type: bool
        value: false
        state: present
      tags: [quick]
    - name: Make side icons smaller
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSTableViewDefaultSizeMode
        type: int
        value: 1
        state: present
      tags: [quick]
    - name: Keep folders on top in desktop
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXSortFoldersFirstOnDesktop
        type: bool
        value: true
        state: present
      tags: [quick]

    # Trackpad
    - name: Switch to sane scrolling direction
      community.general.osx_defaults:
        key: com.apple.swipescrolldirection
        type: bool
        value: false
        state: present
      tags: [quick]

    # TextEdit
    - name: Disable smart quotes
      community.general.osx_defaults:
        domain: com.apple.TextEdit
        key: SmartQuotes
        type: bool
        value: false
        state: present
      tags: [quick]
    - name: Set TextEdit to default to txt
      community.general.osx_defaults:
        domain: com.apple.TextEdit
        key: RichText
        type: bool
        value: false
        state: present
      tags: [quick]

    - name: Disable terminal login message
      file:
        path: "{{ ansible_env.HOME }}/.hushlogin"
        mode: "0644"
        state: touch
      tags: [quick]
