---
- name: Manage edran\'s dotfiles (https://github.com/edran/dotfiles)
  hosts: localhost
  connection: local
  roles:
    - basic
    - dev_basic
    - set_dotfiles
    - dev_python
    # - dev_cpp
    - mopidy
