- name: "chrome | Add Google linux key"
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present
  become: yes
  become_method: sudo

- name: "chrome | Add Chrome repository"
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
  register: chrome_added
  become: yes
  become_method: sudo

- name: "chrome | Install Chrome"
  apt:
    name: "google-chrome-stable"
    state: present
    allow_unauthenticated: yes
  become: yes
  become_method: sudo
  when: chrome_added.changed
