- name: conda | Check if conda is present
  command: which conda
  ignore_errors: yes
  register: conda_present
  failed_when: conda_present.rc > 1
  changed_when: conda_present.rc == 1

- name: conda | Donwload miniconda
  get_url:
    ulr: "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "/tmp/miniconda.sh"
    mode: 654
  when: conda_present.changed

- name: conda | Install miniconda
  shell: "bash /tmp/miniconda.sh -b -p {{ ansible_env.HOME }}/.conda"
  when: conda_present.changed
