- name: docker | Check if docker is present
  command: which docker
  ignore_errors: yes
  register: docker_present
  failed_when: docker_present.rc > 1
  changed_when: docker_present.rc == 1

- name: docker | Add docker gpg keys
  shell: wget -qO- https://get.docker.com/gpg | sudo apt-key add -
  become: yes
  become_method: sudo
  when: docker_present.changed

- name: docker | Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
  become: yes
  become_method: sudo
  when: docker_present.changed

- name: docker | Install Docker
  apt:
    pkg: docker-ce
    update_cache: yes
    allow_unauthenticated: yes
  become: yes
  become_method: sudo
  when: docker_present.changed

- name: docker | Get current local user
  run_once: True
  set_fact:
    ansible_local_user: "{{ lookup('pipe', 'id -un') | d(lookup('pipe', 'whoami'), True) | d(lookup('env', 'USER'), True) |  d(lookup('env', 'user'), True) |  d(lookup('env', 'LOGNAME'), True) }}"
  failed_when: ansible_local_user == ''
  when: docker_present.changed

- name: docker | Add current user to docker group
  user:
    name: "{{ ansible_local_user }}"
    groups: docker
    append: yes
  become: yes
  become_method: sudo
  when: docker_present.changed
