---
- name: MacOS | Expande save panel
  command: "defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true"

- name: MacOS | Expand print panel by default
  command: "defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true"

- name: MacOS | Save to disk (not to iCloud) by default
  command: "defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false"

- name: MacOS | Automatically quit printer app once the print jobs complete
  command: "defaults write com.apple.print.PrintingPrefs \"Quit When Finished\" -bool true"

- name: MacOS | Disable smart quotes
  command: "defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false"

- name: MacOS | Disable smart dashes
  command: "defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false"

- name: MacOS | Enable modal dialogs tab access
  command: "defaults write NSGlobalDomain AppleKeyboardUIMode -int 3"

- name: MacOS | Save screenshots to the desktop
  command: "defaults write com.apple.screencapture location -string \"${HOME}/Pictures/screenshots\""

- name: MacOS | Save screenshots in PNG
  command: "defaults write com.apple.screencapture type -string \"png\""

- name: MacOS | Enable subpixel font rendering on non-Apple LCDs
  command: "defaults write NSGlobalDomain AppleFontSmoothing -int 2"

###############################################################################
# Finder                                                                      #
###############################################################################

- name: MacOS | Show status bar in Finder
  command: "defaults write com.apple.finder ShowStatusBar -bool true"

- name: MacOS | Show path bar in Finder
  command: "defaults write com.apple.finder ShowPathbar -bool true"

# - name: MacOS | Display full POSIX path in Finder
#   command: "defaults write com.apple.finder _FXShowPosixPathInTitle -bool true"

- name: MacOS | Search the current folder by default
  command: "defaults write com.apple.finder FXDefaultSearchScope -string \"SCcf\""

- name: MacOS | Disable the warning when changing a file extension
  command: "defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false"

- name: MacOS | Enable spring loading for directories
  command: "defaults write NSGlobalDomain com.apple.springing.enabled -bool true"

- name: MacOS | Remove the spring loading delay for directories
  command: "defaults write NSGlobalDomain com.apple.springing.delay -float 0.1"

- name: MacOS | Show Library directory
  command: "chflags nohidden {{ ansible_env.HOME }}/Library"

- name: MacOS | Set the dock items size
  command: "defaults write com.apple.dock tilesize -int 30"

- name: MacOS | Use plain text mode for new TextEdit documents
  command: "defaults write com.apple.TextEdit RichText -int 0"

- name: MacOS | Disable Chrome swipe-based navigation
  command: "defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false"
