- include: "emacs_{{ansible_distribution | lower}}.yml"

- include: "tmux_{{ansible_distribution | lower}}.yml"

- include: "conda_{{ansible_distribution | lower}}.yml"

- include: "terminal_{{ansible_distribution | lower}}.yml"

- include: productivity_macosx.yml
  when: ansible_distribution == "MacOSX"

- include: "mosh_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include: "docker_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include: "dropbox_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include: "caps2mods_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include: "chrome_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include: "spotify_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

