- name: "spotify | Add Spotify repository"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    filename: "google-chrome"
    state: present
  register: spotify_added
  become: yes
  become_method: sudo

- name: "spotify | Install Spotify"
  apt:
    name: "spotify-client-qt"
    state: present
    allow_unauthenticated: yes
  become: yes
  become_method: sudo
  when: spotify_added.changed
