---
- name: terminal | Install straighforward packages
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - xclip  # uuuh this requires Xorg...
    - htop
    - tree
    - ranger
    - ppa-purge
    - cowsay
    - lolcat
    - fortune

- name: terminal | Check asciinema package
  command: which asciinema
  register: asciinema_present
  failed_when: asciinema_present.rc > 1
  changed_when: asciinema_present.rc == 1

- name: terminal | Add asciinema repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: "ppa:ubuntu-elisp/ppa"
  register: ansible_added
  when: asciinema_present.changed

- name: terminal | Install asciinema
  become: yes
  become_method: sudo
  apt:
    pkg: asciinema
    state: present
    update_cache: yes
  when: asciinema_present.changed

- name: terminal | Check ag package
  command: which ag
  register: ag_present
  failed_when: ag_present.rc > 1
  changed_when: ag_present.rc == 1

- name: terminal | Install ag build dependencies
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev
  when: ag_present.changed

- name: terminal | Clone ag repo
  git:
    repo: "git://github.com/ggreer/the_silver_searcher"
    dest: "/tmp/ag"
    force: no
    accept_hostkey: yes
  when: ag_present.changed

- name: terminal | Build ag
  command: "./build.sh"
  args:
    chdir: "/tmp/ag"
  when: ag_present.changed

- name: terminal | Install ag
  command: "make install"
  become: yes
  become_method: sudo
  args:
    chdir: "/tmp/ag"
  when: ag_present.changed
