---

- name: terminal | Ensure iterm2 is installed
  homebrew_cask:
    name: iterm2
    state: present
  
- name: terminal | Install straighforward packages
  homebrew:
    pkg: "{{ item }}"
    state: present
  with_items:
    # essential
    - coreutils
    - moreutils
    - findutils
    - homebrew/dupes/grep
    - homebrew/dupes/openssh
    - ssh-copy-id
    # utils
    - mosh
    - git
    - git-lfs
    - gnupg
    - autoconf
    - watch
    - readline
    - wget
    - curl
    - iperf
    - nmap
    - htop
    - tree
    - ranger
    - the_silver_searcher
    - pv
    - ncdu
    - gifsicle
    - reattach-to-user-namespace
    # shell
    - fish
    - zsh
    - bash
    - bash-completion
    # silly
    - archey
    - cowsay
    - lolcat
    - fortune
    - asciinema
