---

- name: terminal | Ensure iterm2 is installed
  homebrew_cask:
    name: iterm2
    state: present
  
- name: terminal | Install straighforward packages
  homebrew:
    pkg: "{{ item }}"
    state: present
  with_items:
    # essential
    - coreutils
    - moreutils
    - findutils
    - grep
    - openssh
    - ssh-copy-id
    # utils
    - mosh
    - git
    - git-lfs
    - gnupg
    - autoconf
    - watch
    - readline
    - wget
    - curl
    - iperf
    - nmap
    - htop
    - tree
    - ranger
    - vifm
    - the_silver_searcher
    - pv
    - ncdu
    - gifsicle
    - reattach-to-user-namespace
    - teensy_loader_cli  # should not be here
    - ical-buddy # needs cron job to get ical calendar to org-agenda
    # shell
    - zsh
    - getantibody/tap/antibody
    - bash
    - bash-completion
    - fish
    # silly
    - archey
    - cowsay
    - lolcat
    - fortune
    - asciinema

# FIXME
# - name: terminal | update antibody plugins script
#  command: "antibody bundle < \"{{ ansible_env.HOME }}/.dotfiles/dots/zsh_plugins\" >~/.zsh_plugins.sh"

- name: terminal | generate zsh_plugins.sh
  command: "antibody update"

# FIXME current these need to run after set_dotfiles
- name: terminal | setup ical2org-agenda launchctl
  command: "launchctl load {{ ansible_env.HOME }}/Library/LaunchAgents/org.nantas.ical2org.plist"

- name: terminal | starts ical2org-agenda service
  command: "launchctl start org.nantas.ical2org"
