---

- name: tiling | Ensure chunkwm tap is installed
  homebrew_tap:
    name: crisidev/homebrew-chunkwm

- name: tiling | Ensure chunkwm is installed
  homebrew:
    pkg: chunkwm
    install_options: with-tmp-logging

- name: tiling | Ensure skhd is installed
  homebrew:
    pkg: koekeishiya/formulae/skhd
    install_options: with-logging

- name: tiling | Ensure bitbar is installed
  homebrew_cask:
    pkg: bitbar

- name: tiling | Ensure .chunkwm is linked
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/dots/macosx/chunkwmrc"
    dest: "{{ ansible_env.HOME }}/.chunkwmrc"
    state: link
    mode: 0755  # needs to be executable for some reason

- name: tiling | Ensure .skhdrc is linked
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/dots/macosx/skhdrc"
    dest: "{{ ansible_env.HOME }}/.skhdrc"
    state: link

- name: tiling | Ensure .bitbar is linked
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/dots/macosx/bitbar"
    dest: "{{ ansible_env.HOME }}/.bitbar"
    state: link


- name: tiling | Check chunkwm service status
  shell: "brew services list | grep 'chunkwm' | tr -s ' ' | cut -d ' ' -f 2"
  register: chunkwm_service
  # if there's no registered service
  failed_when: chunkwm_service.stdout == ""
  changed_when: false

- name: tiling | Ensure chunkwm service is started
  command: "brew services start chunkwm"
  when: chunkwm_service.stdout != "started"

- name: tiling | Check skhd service status
  shell: "brew services list | grep 'skhd' | tr -s ' ' | cut -d ' ' -f 2"
  register: skhd_service
  # if there's no registered service
  failed_when: skhd_service.stdout == ""
  changed_when: false

- name: tiling | Ensure skhd service is started
  command: "brew services start skhd"
  when: skhd_service.stdout != "started"
