- name: Check if Zotero is installed
  stat:
    path: "/opt/zotero/"
  register: zotero_dir
  changed_when: false

- name: Download Zotero
  get_url:
    url: "https://raw.github.com/edran/zotero_installer/master/zotero_installer.sh"
    dest: "/tmp/zotero_installer.sh"
    mode: "u+rwx"
    force: yes
  when: not zotero_dir.stat.exists

- name: Install Zotero
  command: "/tmp/zotero_installer.sh"
  register: install
  become: yes
  become_method: sudo
  failed_when: install.rc > 0
  when: not zotero_dir.stat.exists
