# -*- mode: yaml; eval: (+ansible-yaml-mode);  -*-
---
dotfiles_repo: "https://github.com/edran/dotfiles"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/.dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vim
